In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
import numpy as np
## create array using numpy
arr1=np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [10]:
# 1 Dimensional array
arr2=np.array([1,2,3,4,5])
arr2.reshape(1,5) # 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
# 2Dimensional array
arr2=np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)
print(arr2.shape)


[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [11]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [ ]:
#all ones in matrix
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
arr =np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)# output (2,3)
print(arr.ndim)# output 2
print(arr.size)# output 6
print(arr.dtype)# output int64
print(arr.itemsize)# output 8

[[1 2 3]
 [4 5 6]]
(2, 3)
2
6
int64
8


In [13]:
#numpy vectorize operaations
arr1=np.array([1,2,3,4,5])
arr2=np.array([10,20,30,40,50])

##element wise addition
print(arr1+arr2)

#element wise substraction
print(arr1-arr2)

#element wise multiplication

print(arr1*arr2)

#element wise division
print(arr1/arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [6]:
# Universal Function
arr=np.array([2,3,4,5,6])
## square root
print(np.sqrt(arr))

##Exponential
print(np.exp(arr))

#Sine
print(np.sin(arr))

# natutal log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [12]:
## array slicing and indexing
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(arr)
print(arr[0][0])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1


In [19]:
arr[0][3]

np.int64(4)

In [20]:
arr[2:3]

array([[ 9, 10, 11, 12]])

In [7]:
arr[1:]

array([3, 4, 5, 6])

In [13]:
arr[1:,2:]

array([[ 7,  8],
       [11, 12]])

In [15]:
print(arr[0:2,2:])

[[3 4]
 [7 8]]


In [16]:
print(arr[1:,1:3])

[[ 6  7]
 [10 11]]


In [17]:
#modifiy array elements
arr[0][0]=100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [19]:
#statical concepts  -- Normalization
# to have a mean of 0 and standard division
data=np.array([1,2,3,4,5])

#calculate the mean and stand daviation
mean=np.mean(data)
std_dev=np.std(data)

#Normalization the data

normalized_data=(data-mean)/std_dev
print("Normalixes data:",normalized_data)


Normalixes data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [20]:
data=np.array([1,2,3,4,5,6,7,8,9,10])

# Mean
mean=np.mean(data)
print("Mean: ",mean)

# Median
median=np.median(data)
print("Median: ",median)

#standard deviation
std_dev=np.std(data)
print("standard deviation: ",std_dev)

#Variance
variance=np.var(data)
print("Variance: ",variance)

Mean:  5.5
Median:  5.5
standard deviation:  2.8722813232690143
Variance:  8.25


In [24]:
## logical Operation
data=np.array([1,2,3,4,5,6,7,8,9,10])

data[data>5]

data[(data>=5) &(data<=8)]

array([5, 6, 7, 8])